const GLOW_EFFECTS = {
  ORANGE_PURPLE: {
    LEFT: {
      COLOR: '#f39e8d40',
      X: '20%',
      Y: '-16%',
      RADIUS: '30%',
    },
    RIGHT1: {
      COLOR: '#ffeba824',
      // COLOR: '#4e4bd212',
      // COLOR: 'transparent',
      // COLOR: 'green',
      X: '100%',
      Y: '0',
      RADIUS: '40%',
    },
    MAIN: {
      COLOR: '#4e4bd212',
      // COLOR: 'transparent',
      // COLOR: 'blue',
      X: '78%',
      Y: '4%',
      RADIUS: '40%',
    },
    RIGHT2: {
      COLOR: '#961fb314',
      // COLOR: 'transparent',
      // COLOR: 'tomato',
      X: '90%',
      Y: '15%',
      RADIUS: '30%',
    },
  },
  YELLOW_RED: {
    LEFT: {
      COLOR: '#ffc43b2b',
      X: '20%',
      Y: '-16%',
      RADIUS: '30%',
    },
    RIGHT1: {
      COLOR: '#d4003f03',
      // COLOR: '#4e4bd212',
      // COLOR: 'transparent',
      // COLOR: 'green',
      X: '100%',
      Y: '0',
      RADIUS: '40%',
    },

    MAIN: {
      COLOR: '#f4433621',
      // COLOR: 'transparent',
      // COLOR: 'blue',
      X: '78%',
      Y: '4%',
      RADIUS: '40%',
    },
    RIGHT2: {
      COLOR: '#ff98000a',
      // COLOR: 'transparent',
      // COLOR: 'tomato',
      X: '90%',
      Y: '15%',
      RADIUS: '30%',
    },
  },
  GREY_GREEN: {
    LEFT: {
      COLOR: '#dfcfc6a1',
      X: '20%',
      Y: '-16%',
      RADIUS: '30%',
    },
    RIGHT1: {
      COLOR: '#dbe7e517',
      // COLOR: '#4e4bd212',
      // COLOR: 'transparent',
      // COLOR: 'green',
      X: '100%',
      Y: '0',
      RADIUS: '40%',
    },
    MAIN: {
      COLOR: '#9ad6d630',
      // COLOR: 'transparent',
      // COLOR: 'blue',
      X: '78%',
      Y: '4%',
      RADIUS: '40%',
    },
    RIGHT2: {
      COLOR: '#8ea6bd0f',
      // COLOR: 'transparent',
      // COLOR: 'tomato',
      X: '90%',
      Y: '15%',
      RADIUS: '30%',
    },
  },
  YELLOW_BLUE: {
    LEFT: {
      COLOR: '#ffeb3b2b',
      X: '20%',
      Y: '-16%',
      RADIUS: '30%',
    },
    RIGHT1: {
      COLOR: '#00bcd400',
      // COLOR: '#4e4bd212',
      // COLOR: 'transparent',
      // COLOR: 'green',
      X: '100%',
      Y: '0',
      RADIUS: '40%',
    },
    MAIN: {
      COLOR: '#2196f305',
      // COLOR: 'transparent',
      // COLOR: 'blue',
      X: '78%',
      Y: '4%',
      RADIUS: '40%',
    },
    RIGHT2: {
      COLOR: '#2196f31a',
      // COLOR: 'transparent',
      // COLOR: 'tomato',
      X: '90%',
      Y: '15%',
      RADIUS: '30%',
    },
  },
}

export default GLOW_EFFECTS
