import type { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  schema: 'backend/api/schema.graphql',
  documents: [
    'frontend/core/schemas/pages/user.ts',
    'frontend/core/schemas/pages/user.fragments.ts',
    'frontend/core/schemas/pages/article.fragments.ts',
    'frontend/core/schemas/pages/misc.fragments.ts',
    'frontend/core/schemas/pages/post.ts',
    'frontend/core/schemas/pages/changelog.ts',
    'frontend/core/schemas/pages/doc.ts',
    'frontend/core/schemas/pages/doc.fragments.ts',
    'frontend/core/schemas/pages/community.ts',
    'frontend/core/schemas/pages/action.ts',
    'frontend/core/schemas/pages/misc.ts',
    'frontend/core/schemas/pages/activity.ts',
    'frontend/core/unit/AboutThread/schema.ts',
    'frontend/core/unit/ChangelogThread/schema.ts',
    'frontend/core/unit/CoverEditor/schema.ts',
    'frontend/core/unit/RichEditor/schema.ts',
    'frontend/core/unit/DsbThread/Analysis/WebOverview/schema.ts',
    'frontend/core/unit/DsbThread/Analysis/WebOverview/server.ts',
    'frontend/core/unit/DsbThread/Analysis/RealtimeOnline/schema.ts',
    'frontend/core/unit/DsbThread/schema/admins.ts',
    'frontend/core/unit/DsbThread/Appearance/Theme/schema.ts',
    'frontend/core/unit/DsbThread/schema/appearance.ts',
    'frontend/core/unit/DsbThread/schema/assets.ts',
    'frontend/core/unit/DsbThread/schema/content.ts',
    'frontend/core/unit/PassportEditor/schema.ts',
    'frontend/core/unit/KanbanThread/schema.ts',
    'frontend/core/unit/KanbanThread/fragments.ts',
    'frontend/core/unit/DocCovers/schema.ts',
    'frontend/core/unit/DocCovers/fragments.ts',
    'frontend/core/unit/ArticleSettingMenu/schema.ts',
    'frontend/core/unit/ArticleSettingMenu/fragments.ts',
    'frontend/core/unit/TagSettingEditor/schema.ts',
    'frontend/core/unit/Comments/schema.ts',
    'frontend/core/unit/Comments/fragments.ts',
    'frontend/core/unit/DsbThread/Appearance/Wallpaper/schema.ts',
    'frontend/core/unit/DsbThread/schema/docs.ts',
    'frontend/core/unit/DsbThread/schema/docs.fragments.ts',
    'frontend/core/unit/DsbThread/schema/fragments.ts',
    'frontend/core/unit/DsbThread/schema/integrations.ts',
    'frontend/core/unit/DsbThread/schema/settings.ts',
    'frontend/core/unit/DsbThread/schema/shell.ts',
    'frontend/core/unit/DsbThread/schema/tags.ts',
    'frontend/core/unit/ArticleEditor/schema.ts',
    'frontend/core/unit/ArticleEditor/fragments.ts',
    'frontend/core/unit/PostThread/schema.ts',
    'frontend/core/unit/DsbThread/CMS/Docs/Import/schema.ts',
    'frontend/core/unit/DsbThread/CMS/Docs/Import/fragments.ts',
    'frontend/core/query/viewer.ts',
    'frontend/core/query/mutation/article.ts',
  ],
  pluckConfig: {
    globalGqlIdentifierName: [],
    modules: [
      {
        name: '~/graphql/authoring',
        identifier: 'graphql',
      },
    ],
  },
  generates: {
    'frontend/core/lib/graphql/generated/': {
      preset: 'client',
      presetConfig: {
        fragmentMasking: false,
      },
    },
  },
}

export default config
