/**
 * Rendering target generated by `composeBgRenderSpec`.
 *
 * @example
 * const spec = composeBgRenderSpec(config)
 */
export enum BG_RENDER_TYPE {
  NONE = 'none',
  LINEAR_GRADIENT = 'linear-gradient',
  RADIAL_GRADIENT = 'radial-gradient',
  MESH_GRADIENT = 'mesh-gradient',
  IMAGE = 'image',
}

/**
 * Base fallback gradient colors used when renderer input has no explicit color map.
 *
 * @example
 * composeBgRenderSpec(config).colorStops  // uses these as fallback palette
 */
export const DEFAULT_RENDER_COLORS = ['#fbeede', '#d8b9e3']

/** Canonical pattern scale shared by editor previews and static wallpaper export. */
export const DEFAULT_WALLPAPER_PATTERN_SIZE = '260px auto'

/** Canonical bitmap size shared by wallpaper export and the editor's cover viewport. */
export const DEFAULT_WALLPAPER_EXPORT_SIZE = [1200, 630] as const

/**
 * Pattern overlay color for `WALLPAPER_PATTERN_TONE.LIGHT`.
 *
 * @example
 * patternColor = BG_PATTERN_LIGHT_COLOR
 */
export const BG_PATTERN_LIGHT_COLOR = '#ffffff'

/**
 * Pattern overlay color for `WALLPAPER_PATTERN_TONE.DARK`.
 *
 * @example
 * patternColor = BG_PATTERN_DARK_COLOR
 */
export const BG_PATTERN_DARK_COLOR = '#000000'
