# Generated by packages/contracts/scripts/generate-auth-contract.mjs. Do not edit directly.
defmodule GroupherServer.Auth.Contract do
  @moduledoc """
  Phoenix mirror of the generated public auth protocol contract.

  Auth request
    -> generated contract values
    -> Phoenix and Assets Hub verification
  """

  @codes %{
    invalid_request: "INVALID_REQUEST",
    invalid_csrf: "INVALID_CSRF",
    permission_denied: "PERMISSION_DENIED",
    token_missing: "TOKEN_MISSING",
    token_expired: "TOKEN_EXPIRED",
    token_invalid: "TOKEN_INVALID",
    token_revoked: "TOKEN_REVOKED",
    session_missing: "SESSION_MISSING",
    session_expired: "SESSION_EXPIRED",
    session_revoked: "SESSION_REVOKED",
    session_unavailable: "SESSION_UNAVAILABLE",
    session_conflict: "SESSION_CONFLICT",
    account_blocked: "ACCOUNT_BLOCKED",
    rate_limited: "RATE_LIMITED",
    oauth_binding_not_found: "OAUTH_BINDING_NOT_FOUND",
    oauth_identity_already_linked: "OAUTH_IDENTITY_ALREADY_LINKED",
    oauth_provider_already_linked: "OAUTH_PROVIDER_ALREADY_LINKED",
    oauth_last_login_method: "OAUTH_LAST_LOGIN_METHOD",
    invalid_origin: "INVALID_ORIGIN",
    oauth_provider_unsupported: "OAUTH_PROVIDER_UNSUPPORTED",
    link_intent_unavailable: "LINK_INTENT_UNAVAILABLE",
    oauth_link_invalid_intent: "OAUTH_LINK_INVALID_INTENT",
    oauth_link_replayed: "OAUTH_LINK_REPLAYED",
    oauth_link_invalid_callback: "OAUTH_LINK_INVALID_CALLBACK",
    phoenix_network_error: "PHOENIX_NETWORK_ERROR",
    refresh_unavailable: "REFRESH_UNAVAILABLE",
    oauth_accounts_unavailable: "OAUTH_ACCOUNTS_UNAVAILABLE",
    oauth_link_unavailable: "OAUTH_LINK_UNAVAILABLE",
    oauth_unlink_unavailable: "OAUTH_UNLINK_UNAVAILABLE",
    logout_unavailable: "LOGOUT_UNAVAILABLE",
    service_token_invalid: "SERVICE_TOKEN_INVALID",
    service_scope_forbidden: "SERVICE_SCOPE_FORBIDDEN",
    service_jwks_unavailable: "SERVICE_JWKS_UNAVAILABLE"
  }

  @phoenix_browser_token_claims %{
    issuer: "groupher:phoenix",
    audience: "phoenix:browser-api",
    type: "browser_access"
  }

  @spec all() :: %{atom() => String.t()}
  def all, do: @codes

  for {name, _value} <- @codes do
    @spec unquote(name)() :: String.t()
    def unquote(name)(), do: @codes[unquote(name)]
  end

  @spec phoenix_browser_token_claims() :: %{atom() => String.t()}
  def phoenix_browser_token_claims, do: @phoenix_browser_token_claims

  @spec phoenix_token_issuer() :: String.t()
  def phoenix_token_issuer, do: @phoenix_browser_token_claims.issuer

  @spec phoenix_token_audience() :: String.t()
  def phoenix_token_audience, do: @phoenix_browser_token_claims.audience

  @spec phoenix_token_type() :: String.t()
  def phoenix_token_type, do: @phoenix_browser_token_claims.type
end
