/** @type {import('tailwindcss').Config} */

const lightTokens = require('./lightTokens')
const darkTokens = require('./darkTokens')

module.exports = {
  primary: {
    DEFAULT: lightTokens.primaryColor,
    dark: darkTokens.primaryColor,
  },
  htmlBg: {
    DEFAULT: lightTokens.bannerBg,
  },
  loading: {
    basic: {
      DEFAULT: '#E0E0E0',
    },
    animate: {
      DEFAULT: lightTokens.contentBg,
      dark: darkTokens.contentBg,
    },
  },
  error: {
    title: {
      DEFAULT: lightTokens.primaryColor,
    },
    desc: {
      DEFAULT: lightTokens.primaryColor,
    },
    bg: {
      DEFAULT: lightTokens.contentBoxBg,
    },
  },
  landing: {
    greyBg: {
      DEFAULT: '#fbfbfb',
    },
  },

  font: { DEFAULT: lightTokens.fontColor },
  link: { DEFAULT: lightTokens.link },
  blackActive: { DEFAULT: '#3171DB' },
  divider: { DEFAULT: lightTokens.border },
  alphaBg: { DEFAULT: '#ffffff95' },
  alphaBg2: { DEFAULT: '#fffffff2' },
  hoverBg: { DEFAULT: lightTokens.hoverBg },
  hoverActive: { DEFAULT: 'white' },
  menuHoverBg: { DEFAULT: 'white' },
  lineDivider: { DEFAULT: '#acacacc9' },
  hoverBorder: { DEFAULT: lightTokens.hoverBg },
  hoverLinear: { DEFAULT: 'linear-gradient(315deg, rgba(255, 255, 255, 0) 0%, #fafafa 100%)' },
  menuActive: { DEFAULT: '#e9e9e991' },
  linkHover: { DEFAULT: lightTokens.link },
  heightIcon: { DEFAULT: '#e48a3d' },
  heightGradient: { DEFAULT: 'linear-gradient(90deg, rgb(243, 170, 0) 0%, rgb(228, 62, 41) 100%)' },
  bodyBg: { DEFAULT: lightTokens.contentBg },
  selectionBg: { DEFAULT: '#FFFEDE' },
  textBadge: { DEFAULT: '#e2e2e287' }, // with alpha
  lightText: { DEFAULT: '#999999' },
  hint: { DEFAULT: lightTokens.hint },
  articleCardShadow: { DEFAULT: '0 2px 40px 0 rgb(224 226 228 / 27%)' },
  articleCardHover: { DEFAULT: '#c1c1c1' },
  dashboardBlockOpacity: { DEFAULT: 0.65 },

  rainbow: {
    red: { DEFAULT: '#ca5f4d' },
    redBg: { DEFAULT: '#ffbfba3d' },
    redSoft: { DEFAULT: 'linear-gradient(90deg, #fec0bb33 0%, #f8e4e226 100%)' },

    orange: { DEFAULT: 'orange' },
    orangeBg: { DEFAULT: '#FEF7E8' },
    orangeSoft: { DEFAULT: 'linear-gradient(90deg, #fcb32d26 0%, #f5dfb726 100%)' },

    brown: { DEFAULT: '#8d691e' },
    brownBg: { DEFAULT: '#fff3df' },
    brownSoft: { DEFAULT: 'linear-gradient(90deg, #cf806921 0%, #dbd0d01c 100%)' },

    yellow: { DEFAULT: '#c7b96d' },
    yellowBg: { DEFAULT: '#FEFBE8' },
    yellowSoft: { DEFAULT: 'linear-gradient(90deg, #fffde5 0%, rgb(255 252 241 / 37%) 100%)' },

    green: { DEFAULT: '#699411' },
    greenBg: { DEFAULT: '#eefdd89c' },
    greenSoft: { DEFAULT: 'linear-gradient(90deg, #e3f3cc4a 0%, #f2ffe05c 100%)' },

    greenLight: { DEFAULT: '#79d08f' },
    greenLightBg: { DEFAULT: '#e3f3cc4a' },
    greenLightSoft: { DEFAULT: 'linear-gradient(90deg, #e3f3cc4a 0%, #f2ffe05c 100%)' },

    cyan: { DEFAULT: '#24878C' },
    cyanBg: { DEFAULT: '#e1fcff' },
    cyanSoft: { DEFAULT: 'linear-gradient(90deg, #e1fcff94 0%, #e1fcff5e 100%)' },

    // naming, fix later
    cyanLight: { DEFAULT: '#00B5CC' },
    cyanLightBg: { DEFAULT: '#e1fcff94' },
    cyanLightSoft: { DEFAULT: '#e1fcff94' },

    blue: { DEFAULT: '#5073C6' },
    blueBg: { DEFAULT: '#E7EDF7' },
    blueSoft: { DEFAULT: 'linear-gradient(90deg, #f3f7ff 0%, #f5f8ffb5 100%);' },

    purple: { DEFAULT: '#7d519e' },
    purpleBg: { DEFAULT: '#f7d8fd38' },
    purpleSoft: { DEFAULT: 'linear-gradient(90deg, #f7d8fd38 0%, #f5e5f838 100%)' },

    grey: { DEFAULT: '#106d8a' },

    pink: { DEFAULT: '#b36976' },
    pinkBg: { DEFAULT: '#ffd8ea59' },
    pinkSoft: { DEFAULT: '#ffd8ea59' },

    pinkLite: { DEFAULT: '#82606b' },
    pinkBtnText: { DEFAULT: '#ded0d0' },

    black: { DEFAULT: '#333333' },
    blackRow: { DEFAULT: '#333333' },
    blackBg: { DEFAULT: '#f4f4f4' },
    blackSoft: { DEFAULT: '#f4f4f4' },
  },
  grey: {
    rare: { DEFAULT: '#fafafa' },
    middle: { DEFAULT: '#F1F3F4' },
    hard: { DEFAULT: '#F1F3F4' },
  },
  shadow: {
    md: { DEFAULT: 'rgba(0, 0, 0, 0.03) 0px 6px 24px 0px, rgba(0, 0, 0, 0.05) 0px 0px 0px 1px;' },
    lg: { DEFAULT: '' },
    xl: { DEFAULT: '' },
    xxl: { DEFAULT: 'rgba(149, 157, 165, 0.2) 0px 8px 24px' },
  },
  // inspired by https://endless.design/
  gradientBg: {
    purple: { DEFAULT: 'linear-gradient(152deg,#faf5ff9c 0%,rgb(222 198 243) 100%)' },
    blue: { DEFAULT: 'linear-gradient(310deg,#f6f3ff54 13%,rgb(209 237 255 / 83%) 100%)' },
    green: { DEFAULT: 'linear-gradient(28deg,#fffbf6 0%,rgb(216 240 221 / 80%) 100%)' },
    orange: { DEFAULT: 'linear-gradient(244deg,#fffcf75e 0%,rgb(255 234 217 / 72%) 100%)' },
    pink: { DEFAULT: 'linear-gradient(224deg,#fde4ff24 0%,rgb(255 223 234 / 79%) 100%)' },
    black: { DEFAULT: 'linear-gradient(25deg,#fafafaba 20%,#bdccce63 100%)' },
    cyan: { DEFAULT: 'linear-gradient(213deg,#fffff3ba 13%,#aff5ffc2 100%)' },
    yellow: { DEFAULT: 'linear-gradient(150deg,#ffe5e529 20%,rgb(255 251 216 / 58%) 100%)' },
  },
  header: {
    fg: { DEFAULT: '#8c8c8c' },
    bg: { DEFAULT: lightTokens.bannerBg },
    spliter: { DEFAULT: '#efefef' },
    fixed: { DEFAULT: lightTokens.contentBoxBg },
    tabActive: { DEFAULT: '#EB6224' },
    tabOthers: { DEFAULT: '#849ca0' },
    cardBg: { DEFAULT: '#ffffff' },
    cardBorder: { DEFAULT: '#e6e6e6' },
    cardLogoText: { DEFAULT: 'lightgrey' },
    cardTitle: { DEFAULT: 'darkgrey' },
  },
  banner: {
    title: { DEFAULT: lightTokens.threadTitle },
    bg: { DEFAULT: lightTokens.bannerBg },
    desc: { DEFAULT: lightTokens.descText },
    spliter: { DEFAULT: '#eae9e9' },
    numberDesc: { DEFAULT: '#cccccc' },
    number: { DEFAULT: '#949494' },
    active: { DEFAULT: '#669ede' },
    numberDivider: { DEFAULT: '#eae9e9' },
    numberHoverBg: { DEFAULT: '#f3f3f3' },
  },
  article: {
    // title: lightTokens.threadTitle,
    title: {
      DEFAULT: 'red',
      dark: 'green',
    },
    digest: { DEFAULT: lightTokens.descText },
    info: { DEFAULT: lightTokens.actionText },
    link: { DEFAULT: lightTokens.link },
    linkHover: { DEFAULT: 'orange' },
    reactionTitle: { DEFAULT: '#7f979a' },
    reactionHoverBg: { DEFAULT: '#f3f7f7' },
  },
  content: {
    bg: { DEFAULT: lightTokens.contentBoxBg },
    border: { DEFAULT: '#EEEEEE' },
    cardBg: { DEFAULT: lightTokens.contentBoxBg },
    cardBorder: { DEFAULT: '#e6e6e6' },
    cardBorderHover: { DEFAULT: lightTokens.primaryColor },
  },
  footer: {
    text: { DEFAULT: lightTokens.descText },
    hover: { DEFAULT: '#949CB5' },
    title: { DEFAULT: '#77706B' },
    bottomBg: { DEFAULT: '#252325' },
    shadow: { DEFAULT: 'rgb(241 241 241) 0px 0px 50px 0px inset' },
  },
  drawer: {
    title: { DEFAULT: lightTokens.threadTitle },
    mask: { DEFAULT: 'rgba(31, 34, 37, 0.15)' },
    desc: { DEFAULT: lightTokens.descText },
    font: { DEFAULT: lightTokens.primaryColor },
    bg: { DEFAULT: lightTokens.contentBg },
    shadow: { DEFAULT: '-8px 8px 20px 11px rgb(143 143 143 / 2%)' },
    shadowLite: { DEFAULT: '-8px 8px 20px 11px rgb(143 143 143 / 2%)' },
    closerShadow: { DEFAULT: '-7px 4px 20px 0px rgb(143 143 143 / 2%)' },
    border: { DEFAULT: 'transparent' },
  },
  comment: {
    bg: { DEFAULT: lightTokens.contentBg },
    icon: { DEFAULT: 'grey' },
    didIcon: { DEFAULT: 'orange' },
    title: { DEFAULT: 'grey' },
    username: { DEFAULT: '#7FA7AC' },
    number: { DEFAULT: '#efbc60' },
    floor: { DEFAULT: '#8590a6' },
    reply: { DEFAULT: '#93b3b5' },
    replyBg: { DEFAULT: '#f3f3f3' },
    placeholder: { DEFAULT: '#8c94a3' },
    filter: { DEFAULT: 'grey' },
    filterActive: { DEFAULT: lightTokens.primaryColor },
    action: { DEFAULT: lightTokens.actionText },
    mentionText: { DEFAULT: '#91a4b5' },
    mentionTextBg: { DEFAULT: '#fcffdb' },
    mentionBg: { DEFAULT: '#F9FCFC' },
    mentionBorder: { DEFAULT: lightTokens.primaryColor },
    mentionActiveBg: { DEFAULT: '#F9FCFC' },
    mentionShadow: { DEFAULT: '0px 2px 10px 1px rgba(235, 235, 235, 1)' },
    indentLine: { DEFAULT: '#E7E9ED' },
    indentActive: { DEFAULT: '#B5BCCB' },
  },
  editor: {
    title: { DEFAULT: '#7ea9ad' },
    content: { DEFAULT: '#a6bebf' },
    placeholder: { DEFAULT: '#B3CFD0' },
    headerBg: { DEFAULT: '#F9FCFC' },
    contentBg: { DEFAULT: '#F9FCFC' },
    border: { DEFAULT: '#D6D6D6' },
    borderActive: { DEFAULT: lightTokens.descText },
    borderNormal: { DEFAULT: '#e2eaea' },
    footer: { DEFAULT: '#a6bebf' },
    footerHover: { DEFAULT: '#a6bebf' },
  },
  markdown: {
    title: { DEFAULT: lightTokens.primaryColor },
    fg: { DEFAULT: lightTokens.markdownFont },
    titleBottom: { DEFAULT: lightTokens.primaryColor },
    hrColor: { DEFAULT: '#154452' },
    blockquoteBorder: { DEFAULT: '#b8d0ce' },
    blockquoteFg: { DEFAULT: lightTokens.markdownFont },
    strongFg: { DEFAULT: '#7c999c' },
    strongBg: { DEFAULT: lightTokens.contentBoxBg },
    link: { DEFAULT: lightTokens.link },
    tableBg: { DEFAULT: lightTokens.contentBoxBg },
    tableBg2n: { DEFAULT: lightTokens.contentBoxBg },
    tableborder: { DEFAULT: `1px solid ${lightTokens.contentBoxBg}` },
    taskDone: { DEFAULT: '#528416' },
    taskPeding: { DEFAULT: lightTokens.contentBoxBg },
    br: { DEFAULT: '#e8e8e8' },
  },
  code: {
    bg: { DEFAULT: lightTokens.contentBoxBg },
  },
  shell: {
    link: { DEFAULT: lightTokens.link },
    searchInput: { DEFAULT: lightTokens.descText },
    searchIcon: { DEFAULT: lightTokens.descText },
    barBg: { DEFAULT: lightTokens.contentBoxBg },
    border: { DEFAULT: '#f3f3f3' },
    title: { DEFAULT: lightTokens.threadTitle },
    desc: { DEFAULT: lightTokens.descText },
    activeBg: { DEFAULT: '#F5F5F5' },
  },
  button: {
    primary: { DEFAULT: lightTokens.primaryColor },
    bg: { DEFAULT: lightTokens.primaryColor },
    fg: { DEFAULT: 'white' },
    ghost: { DEFAULT: lightTokens.primaryColor },
    border: { DEFAULT: lightTokens.primaryColor },
    disabledFg: { DEFAULT: lightTokens.descText },
    hoverBg: { DEFAULT: lightTokens.primaryColor },
    activeBg: { DEFAULT: lightTokens.primaryColor },
    clicked: { DEFAULT: lightTokens.primaryColor },
    ghostBorder: { DEFAULT: lightTokens.hint },
    upvoteBorder: { DEFAULT: '#c5c5c5b0' },
    boxShadow: { DEFAULT: 'rgb(202 202 202 / 10%) -1px 1px 16px 2px' },
  },
  navigator: {
    activeBottom: { DEFAULT: lightTokens.primaryColor },
    borderRight: { DEFAULT: lightTokens.bannerBg },
    hoverBg: { DEFAULT: '#eee' },
  },
  popover: {
    bg: { DEFAULT: '#fafafa' }, // '#fffffff2',
    borderColor: { DEFAULT: '#e9e9ea' },
    boxShadow: { DEFAULT: '-3px 2px 20px 0px rgb(58 58 58 / 15%)' },
    activeBorder: { DEFAULT: '#70707094' },
  },
  tags: {
    dotOpacity: { DEFAULT: 0.7 },
    text: { DEFAULT: lightTokens.descText },
  },
  tagger: {
    bg: { DEFAULT: '#fafafa' }, // '#fffffff2',
    borderColor: { DEFAULT: '#e9e9ea' },
    boxShadow: { DEFAULT: '-3px 2px 20px 0px rgb(58 58 58 / 15%)' },
    activeBorder: { DEFAULT: '#70707094' },
  },
  tabs: {
    headerActive: { DEFAULT: '#EB6224' },
    header: { DEFAULT: '#b5b5b5' },
    contentBg: { DEFAULT: '#FFFFFF' },
    headerBg: { DEFAULT: '#F7F9F9' },
    headerActiveTop: { DEFAULT: lightTokens.primaryColor },
    border: { DEFAULT: '#E8E8E8' },
    bottomLine: { DEFAULT: '#E1E4E8' },
  },
  modal: {
    bg: { DEFAULT: lightTokens.contentBoxBg },
    mask: { DEFAULT: 'rgba(31, 34, 37, 0.1)' },
    border: { DEFAULT: lightTokens.primaryColor },
    shadow: { DEFAULT: '-2px 4px 20px 0px rgb(158 157 157 / 23%)' },
    innerSelectBg: { DEFAULT: '#e4eeed45' },
    subPanel: { DEFAULT: '#F5F5F5' },
    subPanelShadow: { DEFAULT: 'none' },
  },
  form: {
    inputBg: { DEFAULT: '#ffffff95' },
    text: { DEFAULT: '#88a4ad' },
    label: { DEFAULT: '#88a4ad' },
    border: { DEFAULT: '#B8C6C0' },
    shadow: { DEFAULT: 'rgba(184, 198, 192, 0.3)' },
  },
  a: {
    hover: { DEFAULT: lightTokens.primaryColor },
    active: { DEFAULT: lightTokens.primaryColor },
  },
  toast: {
    bg: { DEFAULT: lightTokens.contentBoxBg },
    border: { DEFAULT: lightTokens.border },
    title: { DEFAULT: lightTokens.threadTitle },
  },
  table: {
    headerBg: { DEFAULT: '#F8F8F8' },
    headTitle: { DEFAULT: '#949494' },
    text: { DEFAULT: '#949497' },
    border: { DEFAULT: '#F0F0F0' },
    hoverBg: { DEFAULT: '#FAFBFC' },
  },
  avatar: {
    quote: { DEFAULT: '#217470' },
    shadow: { DEFAULT: '0px 0px 4px 0px rgb(0 0 0 / 50%) inset' },
  },
  dashboard: {
    menuCat: { DEFAULT: lightTokens.threadTitle },
    menuTitle: { DEFAULT: lightTokens.descText },
    blockActiveBg: { DEFAULT: '#ffffff95' },
  },
  toggle: {
    shadow: { DEFAULT: '0 0 10px 0 rgb(185 185 185 / 25%) inset' },
    ball: { DEFAULT: 'white' },
  },
  hiddenPanel: {
    DEFAULT: 'linear-gradient(180deg, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 1) 40%)',
  },
}
